# Generated by Django 6.0 on 2025-12-08 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circuit',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('circuit_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('circuit_ref', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('altitude', models.IntegerField(blank=True, null=True)),
                ('url', models.URLField(max_length=500)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['country'], name='core_circui_country_e573a9_idx')],
            },
        ),
        migrations.CreateModel(
            name='Constructor',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('constructor_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('constructor_ref', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.URLField(max_length=500)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='core_constr_name_b746ae_idx')],
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('driver_ref', models.CharField(max_length=100)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('code', models.CharField(blank=True, max_length=3, null=True)),
                ('forename', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.URLField(max_length=500)),
            ],
            options={
                'ordering': ['surname', 'forename'],
                'indexes': [models.Index(fields=['surname'], name='core_driver_surname_9b28dc_idx')],
            },
        ),
        migrations.CreateModel(
            name='ETLRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PARTIAL', 'Partial')], max_length=20)),
                ('seasons_processed', models.JSONField(default=list)),
                ('races_added', models.IntegerField(default=0)),
                ('error_log', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['status'], name='core_etlrun_status_1f1c21_idx'), models.Index(fields=['-started_at'], name='core_etlrun_started_6263bb_idx')],
            },
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('race_id', models.AutoField(primary_key=True, serialize=False)),
                ('season', models.IntegerField()),
                ('round', models.IntegerField()),
                ('race_name', models.CharField(max_length=200)),
                ('race_date', models.DateField()),
                ('race_time', models.TimeField(blank=True, null=True)),
                ('url', models.URLField(max_length=500)),
                ('circuit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='races', to='core.circuit')),
            ],
            options={
                'ordering': ['-season', 'round'],
            },
        ),
        migrations.CreateModel(
            name='Qualifying',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qualifying_id', models.AutoField(primary_key=True, serialize=False)),
                ('position', models.IntegerField()),
                ('q1_time', models.CharField(blank=True, max_length=50, null=True)),
                ('q2_time', models.CharField(blank=True, max_length=50, null=True)),
                ('q3_time', models.CharField(blank=True, max_length=50, null=True)),
                ('constructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qualifying_results', to='core.constructor')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qualifying_results', to='core.driver')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifying_results', to='core.race')),
            ],
            options={
                'verbose_name_plural': 'Qualifying results',
                'ordering': ['race', 'position'],
            },
        ),
        migrations.CreateModel(
            name='DriverStanding',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('standing_id', models.AutoField(primary_key=True, serialize=False)),
                ('points', models.FloatField()),
                ('position', models.IntegerField()),
                ('position_text', models.CharField(max_length=10)),
                ('wins', models.IntegerField()),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='standings', to='core.driver')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_standings', to='core.race')),
            ],
            options={
                'ordering': ['race', 'position'],
            },
        ),
        migrations.CreateModel(
            name='ConstructorStanding',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('standing_id', models.AutoField(primary_key=True, serialize=False)),
                ('points', models.FloatField()),
                ('position', models.IntegerField()),
                ('position_text', models.CharField(max_length=10)),
                ('wins', models.IntegerField()),
                ('constructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='standings', to='core.constructor')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constructor_standings', to='core.race')),
            ],
            options={
                'ordering': ['race', 'position'],
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('result_id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('grid', models.IntegerField()),
                ('position', models.IntegerField(blank=True, null=True)),
                ('position_text', models.CharField(max_length=10)),
                ('position_order', models.IntegerField()),
                ('points', models.FloatField()),
                ('laps', models.IntegerField()),
                ('time_milliseconds', models.BigIntegerField(blank=True, null=True)),
                ('fastest_lap', models.IntegerField(blank=True, null=True)),
                ('fastest_lap_rank', models.IntegerField(blank=True, null=True)),
                ('fastest_lap_time', models.CharField(blank=True, max_length=50, null=True)),
                ('fastest_lap_speed', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(max_length=100)),
                ('constructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='core.constructor')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='core.driver')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.race')),
            ],
            options={
                'ordering': ['race', 'position_order'],
            },
        ),
        migrations.CreateModel(
            name='ConstructorMetrics',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metric_id', models.AutoField(primary_key=True, serialize=False)),
                ('season', models.IntegerField()),
                ('races_entered', models.IntegerField()),
                ('podiums', models.IntegerField()),
                ('wins', models.IntegerField()),
                ('one_two_finishes', models.IntegerField()),
                ('double_dnf', models.IntegerField()),
                ('avg_finish_position', models.FloatField(blank=True, null=True)),
                ('total_points', models.FloatField()),
                ('reliability_rate', models.FloatField()),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('constructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='metrics', to='core.constructor')),
            ],
            options={
                'verbose_name_plural': 'Constructor metrics',
                'ordering': ['-season', '-total_points'],
                'indexes': [models.Index(fields=['constructor'], name='core_constr_constru_f33fa4_idx'), models.Index(fields=['season'], name='core_constr_season_03e81a_idx'), models.Index(fields=['constructor', 'season'], name='core_constr_constru_caf69c_idx')],
                'constraints': [models.UniqueConstraint(fields=('constructor', 'season'), name='unique_constructormetrics_constructor_season')],
            },
        ),
        migrations.CreateModel(
            name='DriverMetrics',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metric_id', models.AutoField(primary_key=True, serialize=False)),
                ('season', models.IntegerField()),
                ('races_entered', models.IntegerField()),
                ('races_finished', models.IntegerField()),
                ('podiums', models.IntegerField()),
                ('wins', models.IntegerField()),
                ('poles', models.IntegerField()),
                ('dnf_count', models.IntegerField()),
                ('avg_finish_position', models.FloatField(blank=True, null=True)),
                ('avg_grid_position', models.FloatField(blank=True, null=True)),
                ('avg_points_per_race', models.FloatField()),
                ('total_points', models.FloatField()),
                ('position_changes_sum', models.IntegerField()),
                ('consistency_score', models.FloatField()),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='metrics', to='core.driver')),
            ],
            options={
                'verbose_name_plural': 'Driver metrics',
                'ordering': ['-season', '-total_points'],
                'indexes': [models.Index(fields=['driver'], name='core_driver_driver__3fccd6_idx'), models.Index(fields=['season'], name='core_driver_season_132be6_idx'), models.Index(fields=['driver', 'season'], name='core_driver_driver__966548_idx')],
                'constraints': [models.UniqueConstraint(fields=('driver', 'season'), name='unique_drivermetrics_driver_season')],
            },
        ),
        migrations.AddIndex(
            model_name='race',
            index=models.Index(fields=['season'], name='core_race_season_918974_idx'),
        ),
        migrations.AddIndex(
            model_name='race',
            index=models.Index(fields=['round'], name='core_race_round_385542_idx'),
        ),
        migrations.AddIndex(
            model_name='race',
            index=models.Index(fields=['season', 'round'], name='core_race_season_002d36_idx'),
        ),
        migrations.AddConstraint(
            model_name='race',
            constraint=models.UniqueConstraint(fields=('season', 'round'), name='unique_season_round'),
        ),
        migrations.AddIndex(
            model_name='qualifying',
            index=models.Index(fields=['race'], name='core_qualif_race_id_47967d_idx'),
        ),
        migrations.AddIndex(
            model_name='qualifying',
            index=models.Index(fields=['driver'], name='core_qualif_driver__0a1682_idx'),
        ),
        migrations.AddIndex(
            model_name='qualifying',
            index=models.Index(fields=['race', 'driver'], name='core_qualif_race_id_d5ca09_idx'),
        ),
        migrations.AddConstraint(
            model_name='qualifying',
            constraint=models.UniqueConstraint(fields=('race', 'driver'), name='unique_qualifying_race_driver'),
        ),
        migrations.AddIndex(
            model_name='driverstanding',
            index=models.Index(fields=['race'], name='core_driver_race_id_7fe78c_idx'),
        ),
        migrations.AddIndex(
            model_name='driverstanding',
            index=models.Index(fields=['driver'], name='core_driver_driver__b676dd_idx'),
        ),
        migrations.AddIndex(
            model_name='driverstanding',
            index=models.Index(fields=['race', 'driver'], name='core_driver_race_id_8bd142_idx'),
        ),
        migrations.AddConstraint(
            model_name='driverstanding',
            constraint=models.UniqueConstraint(fields=('race', 'driver'), name='unique_driverstanding_race_driver'),
        ),
        migrations.AddIndex(
            model_name='constructorstanding',
            index=models.Index(fields=['race'], name='core_constr_race_id_ee19aa_idx'),
        ),
        migrations.AddIndex(
            model_name='constructorstanding',
            index=models.Index(fields=['constructor'], name='core_constr_constru_8375f5_idx'),
        ),
        migrations.AddIndex(
            model_name='constructorstanding',
            index=models.Index(fields=['race', 'constructor'], name='core_constr_race_id_fd6376_idx'),
        ),
        migrations.AddConstraint(
            model_name='constructorstanding',
            constraint=models.UniqueConstraint(fields=('race', 'constructor'), name='unique_constructorstanding_race_constructor'),
        ),
        migrations.AddIndex(
            model_name='result',
            index=models.Index(fields=['race'], name='core_result_race_id_65486e_idx'),
        ),
        migrations.AddIndex(
            model_name='result',
            index=models.Index(fields=['driver'], name='core_result_driver__0d75a2_idx'),
        ),
        migrations.AddIndex(
            model_name='result',
            index=models.Index(fields=['constructor'], name='core_result_constru_48fb8f_idx'),
        ),
        migrations.AddIndex(
            model_name='result',
            index=models.Index(fields=['position'], name='core_result_positio_d115ea_idx'),
        ),
        migrations.AddIndex(
            model_name='result',
            index=models.Index(fields=['race', 'driver'], name='core_result_race_id_0d656a_idx'),
        ),
        migrations.AddConstraint(
            model_name='result',
            constraint=models.UniqueConstraint(fields=('race', 'driver'), name='unique_result_race_driver'),
        ),
    ]
